# Generated by Django 4.2.25 on 2025-10-26 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.CharField(help_text="El comando exacto que el usuario debe decir. Ej: 'Activar detección de obstáculos'", max_length=255, verbose_name='Texto del Comando a Decir')),
                ('explanation_text', models.TextField(blank=True, help_text="Una breve descripción de lo que hace el comando (para la sección 'Ver ejemplos').", verbose_name='Explicación del Comando')),
                ('order', models.PositiveIntegerField(default=0, help_text='El orden en que aparecerá el ejercicio (0 primero, 1 después, etc.).', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ejercicio de Entrenamiento',
                'verbose_name_plural': 'Ejercicios de Entrenamiento',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded_correctly', models.BooleanField(verbose_name='Responded Correctly')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
