# Generated by Django 4.2.25 on 2025-10-26 03:28

import auth_api.utils.validators
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveIntegerField(validators=[auth_api.utils.validators.Validation.validate_age], verbose_name='Edad')),
                ('full_name', models.CharField(max_length=255, validators=[auth_api.utils.validators.Validation.validate_full_name], verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[auth_api.utils.validators.Validation.validate_email], verbose_name='Correo Electrónico')),
                ('emailEmergency', models.EmailField(max_length=254, validators=[auth_api.utils.validators.Validation.validate_email], verbose_name='Correo Electrónico de Emergencia')),
                ('emailAlternative', models.EmailField(blank=True, max_length=254, null=True, validators=[auth_api.utils.validators.Validation.validate_email], verbose_name='Correo Electrónico Alternativo')),
                ('emergency_contact', models.CharField(max_length=255, validators=[auth_api.utils.validators.Validation.validate_phone_number], verbose_name='Contacto de emergencia')),
                ('alternative_contact', models.CharField(blank=True, max_length=255, null=True, validators=[auth_api.utils.validators.Validation.validate_phone_number], verbose_name='Contacto alternativo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
